### PR TITLE
feat: add file overwrite support

### PR DESCRIPTION
**Pull request by adityak74**
This adds support to overwrite the file if required. `overwrite:  true` can be passed in to specify that the file with the same needs to be updated/overwritten. Google Drive will manage the versioning of the file being updated/uploaded.

### CODE REVIEW

**Comment by mathisve** [comment]
Unfortunately we can't pull this if you change the author header to your own name.

**Comment by adityak74** [comment]
@mathisve - Hey, sorry for the changes here. I will make another pull request with just the feature changes. I just had to use it in one of our projects and had to publish the plugin myself. Thanks for being understanding! I will make the PR again. Thanks for the great plugin again!

**Comment by mathisve** [comment]
Sure no worries, I'll reopen the PR so you can make the changes here.

**Comment by adityak74** [comment]
@mathisve - I am closing this one and I have opened a new one with the changes!

**Pull request closed without merging**
